require: rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
