require 'yaml'
require 'pry'
require 'i18n'

require_relative './config/i18n.rb'
require_relative './lib/entities/database.rb'
require_relative './lib/modules/validation.rb'
require_relative './lib/entities/cards/card.rb'
require_relative './lib/entities/cards/usual_card.rb'
require_relative './lib/entities/cards/capitalize_card.rb'
require_relative './lib/entities/cards/virtual_card.rb'
require_relative './lib/entities/account/cards_action.rb'
require_relative './lib/entities/account/account.rb'
require_relative './lib/entities/console.rb'
require_relative './lib/entities/navigator.rb'
