require 'yaml'
require 'pry'
require 'i18n'

require_relative './config/i18n.rb'
require_relative './lib/entities/database.rb'
require_relative './lib/modules/validation.rb'
require_relative './lib/entities/account.rb'
require_relative './lib/entities/console.rb'
require_relative './lib/entities/navigator.rb'
